max_width = 100
indent_style = "Block"
use_try_shorthand = true
reorder_impl_items = true
use_small_heuristics = "Max"
imports_granularity = "Crate"
use_field_init_shorthand = true
match_block_trailing_comma = true
