name: CI-RS

on:
  push:
    paths:
      - "**/.github/workflows/ci-rs.yml"
      - "**/Cargo.lock"
      - "**/src/**"
      - "**/Cargo.toml"
      - "**/rust-toolchain"
      - "**/.taplo.toml"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  # Set more verbose terminal output
  CARGO_TERM_VERBOSE: true
  RUST_BACKTRACE: 1

# Cancel old builds on new commit for same workflow + branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci-rs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust-toolchain:
          - stable 

    steps:
      - name: Get source code
        uses: actions/checkout@v3

      - name: Setup ${{ matrix.rust-toolchain }} rust toolchain with caching
        uses: brndnmtthws/rust-action@v1
        with:
          toolchain: ${{ matrix.rust-toolchain }}
          components: rustfmt, clippy
          enable-sccache: "true"

      - name: Build
        run: cargo build --release 

      - name: Test
        run: cargo test --release 

      - name: Lint
        run: cargo fmt --all -- --check
        # && cargo clippy --verbose -- -D warnings
